#:schema node_modules/wrangler/config-schema.json
name = "cf-neon-cron"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["*/4 * * * *"] # Runs every 4 minutes
